name: lint

on:
  pull_request:
  push:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy

      - name: Cargo clippy
        run: cargo clippy --all-targets -- -D warnings
